-- Genericas só para conferir se os dados foram inseridos corretamente
SELECT * FROM ESTOQUE;
SELECT * FROM LOCALIZACAO_PLATELEIRAS;
SELECT * FROM PLATELEIRAS;
SELECT * FROM CATEGORIA_PLATELEIRAS;
SELECT * FROM RELACIONAMENTO_PLATELEIRAS_CATEGORIAS;
SELECT * FROM PECAS;
SELECT * FROM MOVIMENTACAO_ESTOQUE;

-- Consulta 1
EXPLAIN QUERY PLAN
SELECT ID_PECA, CODIGO_SKU, NOME_PECA, PRECO, QUANTIDADE_ESTOQUE
FROM PECAS
WHERE QUANTIDADE_ESTOQUE < 15
AND PRECO BETWEEN 50.00 AND 200.00;

SELECT ID_PECA, CODIGO_SKU, NOME_PECA, PRECO, QUANTIDADE_ESTOQUE
FROM PECAS
WHERE QUANTIDADE_ESTOQUE < 15
AND PRECO BETWEEN 50.00 AND 200.00;


-- Consulta 2
EXPLAIN QUERY PLAN
SELECT p.ID_PLATELEIRAS, pr.NOME_PLATELEIRA, COUNT(*) AS TOTAL_PECAS, AVG(p.PRECO) AS PRECO_MEDIO
FROM PECAS p
JOIN PLATELEIRAS pr ON p.ID_PLATELEIRAS = pr.ID_PLATELEIRAS
GROUP BY p.ID_PLATELEIRAS, pr.NOME_PLATELEIRA;

SELECT p.ID_PLATELEIRAS, pr.NOME_PLATELEIRA, COUNT(*) AS TOTAL_PECAS, AVG(p.PRECO) AS PRECO_MEDIO
FROM PECAS p
JOIN PLATELEIRAS pr ON p.ID_PLATELEIRAS = pr.ID_PLATELEIRAS
GROUP BY p.ID_PLATELEIRAS, pr.NOME_PLATELEIRA;


-- Consulta 3
EXPLAIN QUERY PLAN
SELECT TIPO_MOVIMENTACAO, SUM(QUANTIDADE) AS TOTAL_MOVIMENTADO, COUNT(*) AS TOTAL_LANCAMENTOS
FROM MOVIMENTACAO_ESTOQUE
WHERE DATA_MOVIMENTACAO BETWEEN '2025-01-01 00:00:00' AND '2025-06-30 23:59:59'
GROUP BY TIPO_MOVIMENTACAO;

SELECT TIPO_MOVIMENTACAO, SUM(QUANTIDADE) AS TOTAL_MOVIMENTADO, COUNT(*) AS TOTAL_LANCAMENTOS
FROM MOVIMENTACAO_ESTOQUE
WHERE DATA_MOVIMENTACAO BETWEEN '2025-01-01 00:00:00' AND '2025-06-30 23:59:59'
GROUP BY TIPO_MOVIMENTACAO;


-- Consulta 4
EXPLAIN QUERY PLAN
SELECT
    e.NOME_ESTOQUE,
    SUM(p.PRECO * p.QUANTIDADE_ESTOQUE) AS FORTUNA_PARADA,
    SUM(p.QUANTIDADE_ESTOQUE) AS TOTAL_ITENS
FROM ESTOQUE e
JOIN LOCALIZACAO_PLATELEIRAS lp ON e.ID_ESTOQUE = lp.ID_ESTOQUE
JOIN PLATELEIRAS pr ON lp.ID_LOCALIZACAO_PLATELEIRA = pr.ID_LOCALIZACAO_PLATELEIRA
JOIN PECAS p ON pr.ID_PLATELEIRAS = p.ID_PLATELEIRAS
GROUP BY e.ID_ESTOQUE, e.NOME_ESTOQUE;

SELECT
    e.NOME_ESTOQUE,
    SUM(p.PRECO * p.QUANTIDADE_ESTOQUE) AS FORTUNA_PARADA,
    SUM(p.QUANTIDADE_ESTOQUE) AS TOTAL_ITENS
FROM ESTOQUE e
JOIN LOCALIZACAO_PLATELEIRAS lp ON e.ID_ESTOQUE = lp.ID_ESTOQUE
JOIN PLATELEIRAS pr ON lp.ID_LOCALIZACAO_PLATELEIRA = pr.ID_LOCALIZACAO_PLATELEIRA
JOIN PECAS p ON pr.ID_PLATELEIRAS = p.ID_PLATELEIRAS
GROUP BY e.ID_ESTOQUE, e.NOME_ESTOQUE;
