SELECT * FROM ESTOQUE;
SELECT * FROM LOCALIZACAO_PLATELEIRAS;
SELECT * FROM PLATELEIRAS;
SELECT * FROM CATEGORIA_PLATELEIRAS;
SELECT * FROM RELACIONAMENTO_PLATELEIRAS_CATEGORIAS;
SELECT * FROM PECAS;
SELECT * FROM MOVIMENTACAO_ESTOQUE;
