DROP TABLE IF EXISTS CATEGORIA_PLATELEIRAS;
DROP TABLE IF EXISTS PLATELEIRAS;
DROP TABLE IF EXISTS LOCALIZACAO_PLATELEIRAS;
DROP TABLE IF EXISTS ESTOQUE;
DROP TABLE IF EXISTS RELACIONAMENTO_PLATELEIRAS_CATEGORIAS;
DROP TABLE IF EXISTS PECAS;
DROP TABLE IF EXISTS MOVIMENTACAO_ESTOQUE;
