CREATE TABLE ESTOQUE(
	ID_ESTOQUE INTEGER PRIMARY KEY AUTOINCREMENT,
	NOME_ESTOQUE VARCHAR(100) NOT NULL,
	CAPACIDADE INT NOT NULL,
	LOCALIDADE_ESTOQUE VARCHAR(255) NOT NULL
);

CREATE TABLE LOCALIZACAO_PLATELEIRAS(
	ID_LOCALIZACAO_PLATELEIRA INTEGER PRIMARY KEY AUTOINCREMENT,
	CODIGO_INTERNO INT NOT NULL UNIQUE,
	DESCRICAO_LOCALIZACAO VARCHAR(255),
	ID_ESTOQUE INT REFERENCES ESTOQUE(ID_ESTOQUE)
);

CREATE TABLE CATEGORIA_PLATELEIRAS(
	ID_CATEGORIA_PLATELEIRA INTEGER PRIMARY KEY AUTOINCREMENT,
	CATEGORIA VARCHAR(100) NOT NULL UNIQUE,
	DESCRICAO_CATEGORIA VARCHAR(255)
);

CREATE TABLE PLATELEIRAS(
	ID_PLATELEIRAS INTEGER PRIMARY KEY AUTOINCREMENT,
	NOME_PLATELEIRA VARCHAR(100) UNIQUE,
	ID_LOCALIZACAO_PLATELEIRA INT REFERENCES LOCALIZACAO_PLATELEIRAS(ID_LOCALIZACAO_PLATELEIRA)
);

CREATE TABLE RELACIONAMENTO_PLATELEIRAS_CATEGORIAS(
	ID_PLATELEIRAS REFERENCES PLATELEIRAS(ID_PLATELEIRAS),
	ID_CATEGORIA_PLATELEIRA REFERENCES CATEGORIA_PLATELEIRAS(ID_CATEGORIA_PLATELEIRA),
	PRIMARY KEY (ID_PLATELEIRAS, ID_CATEGORIA_PLATELEIRA)
);

CREATE TABLE PECAS(
    ID_PECA INTEGER PRIMARY KEY AUTOINCREMENT,
    CODIGO_SKU VARCHAR(50) NOT NULL UNIQUE,
    NOME_PECA VARCHAR(150) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    ID_PLATELEIRAS INT REFERENCES PLATELEIRAS(ID_PLATELEIRAS)
);

CREATE TABLE MOVIMENTACAO_ESTOQUE(
    ID_MOVIMENTACAO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PECA INT NOT NULL REFERENCES PECAS(ID_PECA),
    TIPO_MOVIMENTACAO VARCHAR(10) NOT NULL CHECK (TIPO_MOVIMENTACAO IN ('ENTRADA', 'SAIDA')),
    QUANTIDADE INT NOT NULL,
    DATA_MOVIMENTACAO DATETIME NOT NULL,
    DESCRICAO VARCHAR(255)
);
